site_name: self-dsl
theme: readthedocs
markdown_extensions:
 - codehilite
 - plantuml
pages:
 - 'index.md'
 - 'motivation.md'
 - 'basics.md'
 - Xtext:
    - {'Eclipse':'xtext_eclipse.md'}
    - {'Xtext Project Setup':'xtext_project_setup.md'}
    - {'A First Grammar':'xtext_a_first_grammar.md'}
    - {'Auto Formatting':'xtext_auto_formatting.md'}
    - {'Model Validation':'xtext_model_validation.md'}
    - {'Quickfixes':'xtext_quickfixes.md'}
    - {'Code Generation (with Xtend)':'xtext_code_generation_xtend.md'}
 - TextX:
    - {'TextX Project Setup':'textx_project_setup.md'}
 - 'references.md'


